### ISSUE TITLE
Returning wrong locale sometimes

### ISSUE THREAD

**Issue by fullofcaffeine** [iain/http_accept_language#32]
I have the following code in my Rails app's ApplicationController:

```
before_filter :set_locale
```

And the method definition:

```
  def set_locale
  logger.warn("*** Available locales: #{I18n.available_locales}")
    logger.warn("*** Preferred language:  #{http_accept_language.preferred_language_from(I18n.available_locales)}")
    I18n.locale = (params[:locale] || http_accept_language.preferred_language_from(I18n.available_locales) || I18n.default_locale)
  end
```

I have two locales in the app as of now: :en and :pt. If I setup Portuguese to take precedence in my user agent (Chrome) and reload the page, sometimes it still returns english, even though the it's set to Portuguese.

It looks as if some of the unicorn workers still have the I18n.locale cached somehow. Would that be possible?

Any insights would be greatly appreciated!

**Comment by k0nserv** [comment]
We are still seeing this issue on version 2.0.5 using rails 4.2 and unicorn. We haven't been able to reproduce it reliably either

**Comment by dgilperez** [comment]
Same over here.
