### ISSUE TITLE
Please, release an updated version of the gem

### ISSUE THREAD

**Issue by 907th** [iain/http_accept_language#53]
A latest version from rubygems.org (2.0.5) doesn't contain some very appreciated fixes! Please, release a new minor version!

E.g. 2.0.5 doesn't contain a [fallback to a default locale in AutoLocale helper module](https://github.com/iain/http_accept_language/blob/master/lib/http_accept_language/auto_locale.rb#L14).

**Comment by vasilakisfil** [comment]
@iain can you please publish a new version ?

**Comment by iain** [comment]
Done, v2.1.0 is out.

**Comment by 907th** [comment]
@iain Thank you!
