### ISSUE TITLE
not working in rails 5.1. Due to removed before_filter

### ISSUE THREAD

**Issue by gogo52cn** [iain/http_accept_language#63]
not working in rails 5.1. Due to removed before_filter

**Comment by AntoineMP** [comment]
Now that rails 5.1 is out, this is an emergency....

**Comment by nashby** [comment]
@gogo52cn 2.2.1 is released with Rails 5 support. Can you please check it?

**Comment by ntnmrndn** [comment]
@nashby  It  works for me.
