### ISSUE TITLE
Request for maintainer status

### ISSUE THREAD

**Issue by movermeyer** [iain/http_accept_language#77]
Hello @iain,

I'm requesting that I be granted "maintainer" status over `http_accept_language`.

I'm hoping to exercise more control over the codebase than I feel I can as an outside contributor.

As part of my full-time work at Shopify, I develop and maintain i18n libraries within the Ruby/Rails ecosystem.

For example, I am the maintainer of [`ruby-i18n/ruby-cldr`](https://github.com/ruby-i18n/ruby-cldr), and am currently the [#7 contributor to `ruby-i18n/i18n`](https://github.com/ruby-i18n/i18n/graphs/contributors). I've also contributed minor fixes to [`rails-i18n`](https://github.com/svenfuchs/rails-i18n) and Rails itself. I also maintain `shopify-i18n`, Shopify's (currently internal) i18n/l10n library.

Of course, I would continue to accept and appreciate any collaboration from you, and will treat your previous contributions with respect.

**I'm hoping that you'll allow me this control over the project, or at the very least, start a discussion around how I can gain such control over time.**

The rest of this issue gives some more details about who I am, and what I hope to do with more control over the future of `http_accept_language`.

----

### My vision for `http_accept_language`

I want `http_accept_language` to be a solid foundational library upon the Ruby/Rails ecosystem can depend to provide easy and accurate locale resolution.

Note that I do not wish to expand the scope of `http_accept_language`.

### Some examples of changes I want to make

`http_accept_language`-specific changes:
* Fix #55, so that `http_accept_language` can be used correctly with Chinese locales
* [Long term] Transfer the repo to the `ruby-i18n` organization (i.e., `ruby-i18n/http_accept_language`) to ensure that it has more consistent maintenance going forward. 

General repos changes:
* Add GitHub PR and Issue templates
* Add a CHANGELOG and [LICENSE](https://github.com/iain/http_accept_language/issues/72) file
* Introduce RuboCop to CI, and fix all linting issues
* Change the default branch from `master` to `main`
* Migrate from TravisCI to GitHub Actions, and test against all versions of Ruby
* Add a CONTRIBUTING guide

### My open source CV

I'm not new to the world of open-source maintainership. Beyond those already mentioned, I'm a maintainer/contributor of several well-used libraries in other ecosystems, including:

* [`ciso8601`](https://github.com/closeio/ciso8601) a foundational Python library for parsing ISO 8601 timestamps quickly.
  * It's in the top-1000 most downloaded Python libraries 📈

I also regularly contribute bug reports and bug fixes to all FOSS software I use.

Beyond that, I've been working as a Software Developer for 12 years now. For the past 4, I've been working on i18n systems at Shopify.

### My open source values

* Users should have extreme confidence when upgrading:
  * Maintain backwards compatibility.
    * Breaking changes should be avoided whenever possible.
    * If necessary, should only happen alongside major version bumps, and should have trivial, (preferably automatable) migration paths
  * Keep libraries small in scope, and provide strong invariants that users can always rely on going into the future
  * Follow [the spirit of] [SemVer](https://semver.org/) and [Keep a Changelog](https://keepachangelog.com/)
* Document and support the path to contribution
* Prefer permissive FOSS licenses, but any [FOSS license](https://opensource.org/licenses) is 👌 (`http_accept_language` is MIT 👍)
  * I include this to express my commitment to "open source", which doesn't include licenses with restrictions on who can use the code

### What I'm asking for

* To be added as a ["Collaborator"](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) on `iain/http_accept_language`
* Eventually (when you're comfortable):
  * To have you [transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) `iain/http_accept_language` to the `ruby-i18n` GitHub organization (i.e., `ruby-i18n/http_accept_language`)
  * To have you give me whatever keys are needed to be able to publish a new version to [RubyGems](https://rubygems.org/gems/http_accept_language)

**I'm hoping that you'll allow me this control over the project, or at the very least, start a discussion around how I can gain such control over time.**

**Comment by DouweM** [comment]
@movermeyer Thanks for stepping up, I'm supportive! I took over maintenance from @iain in 2012, but lost interest and project access in 2017. I've been saddened by the lack of activity since, but as I'm not longer working with Rails I wasn't able to change that either. I don't know if @iain still watches this project (I don't think he did during the few years I was involved). The best way to reach him may be over Twitter: https://twitter.com/iain_nl.

**Comment by ghost** [comment]
If there is no response, maybe start a fork at ruby-i18n for now?

**Comment by movermeyer** [comment]
After no response, I'm rescinding this offer. I've moved on.
